mysql:
    container_name: stockstation_mysql
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
        - "3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_USER: "srsusr"
        MYSQL_PASSWORD: "srs"
        MYSQL_DATABASE: "stockstation"

redis:
    container_name: stockstation_redis
    image: redis
    ports:
        - "6379"

statsd:
    container_name: stockstation_statsd
    image: hypnza/statsd_dumpmessages
    ports:
        - "8125/udp"
