'use strict';

module.exports = {
    // home route
    VIEW_HOME_PAGE: 'VIEW_HOME_PAGE',

    //user admin route permission
    VIEW_USERS: 'VIEW_USERS',
    VIEW_USER_DETAILS: 'VIEW_USER_DETAILS',
    CREATE_USER: 'CREATE_USER',
    SAVE_USER: 'SAVE_USER_DETAILS',
    UPDATE_USER: 'UPDATE_USER_DETAILS',

    // role route
    VIEW_ROLES: 'VIEW_ROLES',
    EDIT_ROLE: 'EDIT_ROLE',
    SAVE_ROLE: 'SAVE_ROLE',
    UPDATE_ROLE: 'UPDATE_ROLE',
    VIEW_ROLE_PERMISSIONS: 'VIEW_ROLE_PERMISSIONS',
    CREATE_ROLE_PERMISSIONS: 'CREATE_ROLE_PERMISSIONS',
    SAVE_ROLE_PERMISSIONS: 'SAVE_ROLE_PERMISSIONS',
    REMOVE_ROLE_PERMISSIONS: 'REMOVE_ROLE_PERMISSIONS',

    // permission route
    VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',
    EDIT_PERMISSIONS: 'EDIT_PERMISSIONS',
    CREATE_PERMISSION: 'CREATE_PERMISSION',
    SAVE_PERMISSION: 'SAVE_PERMISSION',
    UPDATE_PERMISSION: 'UPDATE_PERMISSION',
    UPDATE_PERMISSION_STATUS: 'UPDATE_PERMISSION_STATUS',

    // inbound route
    VIEW_INBOUND: 'VIEW_INBOUND',
    VIEW_INBOUND_DETAILS: 'VIEW_INBOUND_DETAILS',

    // outbound route
    VIEW_OUTBOUND: 'VIEW_OUTBOUND',
    VIEW_OUTBOUND_DETAILS: 'VIEW_OUTBOUND_DETAILS',
};

